name: MCRepl
main: com.dumptruckman.mcrepl.MCRepl
version: @plugin_version@

commands:
  mcrepl:
    description: Starts a Java REPL instance
    permission: mcrepl.repl

permissions:
  mcrepl.use:
    default: op
  mcrepl.modal:
    default: true